### PR TITLE
[Hive3]Update dependencies for TDP 1.1

### PR DESCRIPTION
**Pull request by PACordonnier**
Relates to https://github.com/TOSIT-IO/TDP/pull/90

### CODE REVIEW

**Comment by PACordonnier** [comment]
My branch must be rebased upon current 3.1.3-TDP, I didn't want to do it yet
Also, I should include backport needed in https://github.com/TOSIT-IO/hive/pull/10

**Comment by Pierrotws** [comment]
has been cleaned and rebased

**Comment by PACordonnier** [comment]
Now fixes #9, #12, #16

**Comment by PACordonnier** [comment]
Added HIVE-21777 due to building issues

**Pull request merged**
