### PR TITLE
build: replace conjars repo with mirror

### LINKED ISSUE #4: Build fails due to conjars repo being down
I've started building "hive 2-3" which fails due to a Conjars repo being down.

Obviously it can work on your machine if your current `~/.m2/repository` contains needed jars.

I don't understand how previous builds worked since conjar seems to be down since march 2021, see announcement here

https://groups.google.com/g/cascading-user/c/qAQvajapawI

More info on how to fix here https://conjars.wensel.net/

### PR DESCRIPTION
**Pull request by PACordonnier**
#### Which issue(s) this PR fixes

Fixes #4 

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Review by mehdibn — APPROVED** [review]

**Comment by rpignolet** [comment]
I try building Hive 2 with your PR:

```
[INFO] ---------------------< org.apache.hive:hive-exec >----------------------
[INFO] Building Hive Query Language 2.3.9-1.0                           [15/37]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from conjars: http://conjars.wensel.net/repo/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.pom
[WARNING] The POM for org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-archives/2.7.2/hadoop-archives-2.7.2.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/orc/orc-tools/1.3.4/orc-tools-1.3.4.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-all/2.4.4/groovy-all-2.4.4.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/calcite/calcite-core/1.10.0/calcite-core-1.10.0.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/calcite/calcite-linq4j/1.10.0/calcite-linq4j-1.10.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-archives/2.7.2/hadoop-archives-2.7.2.jar (22 kB at 94 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/calcite/calcite-druid/1.10.0/calcite-druid-1.10.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/orc/orc-tools/1.3.4/orc-tools-1.3.4.jar (44 kB at 166 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/calcite/avatica/avatica/1.8.0/avatica-1.8.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/calcite/calcite-druid/1.10.0/calcite-druid-1.10.0.jar (97 kB at 266 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/calcite/avatica/avatica-metrics/1.8.0/avatica-metrics-1.8.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/calcite/avatica/avatica-metrics/1.8.0/avatica-metrics-1.8.0.jar (20 kB at 51 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/parquet/parquet-column/1.8.1/parquet-column-1.8.1-tests.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/calcite/calcite-linq4j/1.10.0/calcite-linq4j-1.10.0.jar (482 kB at 1.1 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/parquet/parquet-common/1.8.1/parquet-common-1.8.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/parquet/parquet-common/1.8.1/parquet-common-1.8.1.jar (39 kB at 85 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/parquet/parquet-column/1.8.1/parquet-column-1.8.1-tests.jar (184 kB at 405 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/parquet/parquet-encoding/1.8.1/parquet-encoding-1.8.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/parquet/parquet-encoding/1.8.1/parquet-encoding-1.8.1.jar (285 kB at 539 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/calcite/calcite-core/1.10.0/calcite-core-1.10.0.jar (4.1 MB at 5.6 MB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/calcite/avatica/avatica/1.8.0/avatica-1.8.0.jar (5.2 MB at 6.6 MB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-all/2.4.4/groovy-all-2.4.4.jar (7.0 MB at 8.4 MB/s)
Downloading from conjars: http://conjars.wensel.net/repo/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Hive 2.3.9-1.0:
[INFO] 
[INFO] Hive ............................................... SUCCESS [  0.721 s]
[INFO] Hive Shims Common .................................. SUCCESS [  1.529 s]
[INFO] Hive Shims 0.23 .................................... SUCCESS [  1.125 s]
[INFO] Hive Shims Scheduler ............................... SUCCESS [  0.396 s]
[INFO] Hive Shims ......................................... SUCCESS [  0.225 s]
[INFO] Hive Common ........................................ SUCCESS [  1.834 s]
[INFO] Hive Service RPC ................................... SUCCESS [  0.874 s]
[INFO] Hive Serde ......................................... SUCCESS [  1.471 s]
[INFO] Hive Metastore ..................................... SUCCESS [  6.702 s]
[INFO] Hive Vector-Code-Gen Utilities ..................... SUCCESS [  0.103 s]
[INFO] Hive Llap Common ................................... SUCCESS [  0.897 s]
[INFO] Hive Llap Client ................................... SUCCESS [  0.557 s]
[INFO] Hive Llap Tez ...................................... SUCCESS [  0.651 s]
[INFO] Spark Remote Client ................................ SUCCESS [  1.354 s]
[INFO] Hive Query Language ................................ FAILURE [  1.762 s]
[INFO] Hive Llap Server ................................... SKIPPED
[INFO] Hive Service ....................................... SKIPPED
[INFO] Hive Accumulo Handler .............................. SKIPPED
[INFO] Hive JDBC .......................................... SKIPPED
[INFO] Hive Beeline ....................................... SKIPPED
[INFO] Hive CLI ........................................... SKIPPED
[INFO] Hive Contrib ....................................... SKIPPED
[INFO] Hive Druid Handler ................................. SKIPPED
[INFO] Hive HBase Handler ................................. SKIPPED
[INFO] Hive JDBC Handler .................................. SKIPPED
[INFO] Hive HCatalog ...................................... SKIPPED
[INFO] Hive HCatalog Core ................................. SKIPPED
[INFO] Hive HCatalog Pig Adapter .......................... SKIPPED
[INFO] Hive HCatalog Server Extensions .................... SKIPPED
[INFO] Hive HCatalog Webhcat Java Client .................. SKIPPED
[INFO] Hive HCatalog Webhcat .............................. SKIPPED
[INFO] Hive HCatalog Streaming ............................ SKIPPED
[INFO] Hive HPL/SQL ....................................... SKIPPED
[INFO] Hive Llap External Client .......................... SKIPPED
[INFO] Hive Shims Aggregator .............................. SKIPPED
[INFO] Hive TestUtils ..................................... SKIPPED
[INFO] Hive Packaging ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.445 s
[INFO] Finished at: 2023-05-26T16:14:57Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hive-exec: Could not resolve dependencies for project org.apache.hive:hive-exec:jar:2.3.9-1.0: Could not find artifact org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hive-exec
```

This URL is not working: http://conjars.wensel.net/repo/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.pom.

**Comment by PACordonnier** [comment]
Yes, see https://github.com/TOSIT-IO/hive/issues/6

**Comment by PACordonnier** [comment]
I'm realising that you showed us earlier that the only use for conjar repo is for this dependency. So seems like the PR is useless as we can't download it anyway.

**Comment by rpignolet** [comment]
I use the branch `branch-2.3-TDP` in order to confirm if this PR is useful.

I download POM and JAR for `pentaho-aggdesigner` dependencies manually as you said:

```bash
mkdir -p m2/org/pentaho/pentaho-aggdesigner{,-algorithm}/5.1.5-jhyde
wget -P m2/org/pentaho/pentaho-aggdesigner/5.1.5-jhyde 'https://repository.mapr.com/nexus/content/groups/mapr-public/conjars/org/pentaho/pentaho-aggdesigner/5.1.5-jhyde/pentaho-aggdesigner-5.1.5-jhyde.pom'
wget -P m2/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde 'https://repository.mapr.com/nexus/content/groups/mapr-public/conjars/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.jar'
wget -P m2/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde 'https://repository.mapr.com/nexus/content/groups/mapr-public/conjars/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.pom'
```

I have a new issue:

```
[INFO] --------------------< org.apache.hive:hive-service >--------------------
[INFO] Building Hive Service 2.3.9-1.0                                  [17/37]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from conjars: http://conjars.org/repo/org/apache/directory/client/ldap/ldap-client-api/0.1-SNAPSHOT/maven-metadata.xml
Downloading from apache.snapshots: http://repository.apache.org/snapshots/org/apache/directory/client/ldap/ldap-client-api/0.1-SNAPSHOT/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/directory/client/ldap/ldap-client-api/0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.apache.directory.client.ldap:ldap-client-api:0.1-SNAPSHOT/maven-metadata.xml from/to conjars (http://conjars.org/repo): Access denied to: http://conjars.org/repo/org/apache/directory/client/ldap/ldap-client-api/0.1-SNAPSHOT/maven-metadata.xml , ReasonPhrase:Forbidden.
[WARNING] Failure to transfer org.apache.directory.client.ldap:ldap-client-api:0.1-SNAPSHOT/maven-metadata.xml from http://conjars.org/repo was cached in the local repository, resolution will not be reattempted until the update interval of conjars has elapsed or updates are forced. Original error: Could not transfer metadata org.apache.directory.client.ldap:ldap-client-api:0.1-SNAPSHOT/maven-metadata.xml from/to conjars (http://conjars.org/repo): Access denied to: http://conjars.org/repo/org/apache/directory/client/ldap/ldap-client-api/0.1-SNAPSHOT/maven-metadata.xml , ReasonPhrase:Forbidden.
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/directory/client/ldap/ldap-client-api/0.1-SNAPSHOT/ldap-client-api-0.1-SNAPSHOT.pom
Downloading from conjars: http://conjars.org/repo/org/apache/directory/client/ldap/ldap-client-api/0.1-SNAPSHOT/ldap-client-api-0.1-SNAPSHOT.pom
Downloading from apache.snapshots: http://repository.apache.org/snapshots/org/apache/directory/client/ldap/ldap-client-api/0.1-SNAPSHOT/ldap-client-api-0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Hive 2.3.9-1.0:
[INFO] 
[INFO] Hive ............................................... SUCCESS [  0.706 s]
[INFO] Hive Shims Common .................................. SUCCESS [  1.458 s]
[INFO] Hive Shims 0.23 .................................... SUCCESS [  1.060 s]
[INFO] Hive Shims Scheduler ............................... SUCCESS [  0.350 s]
[INFO] Hive Shims ......................................... SUCCESS [  0.263 s]
[INFO] Hive Common ........................................ SUCCESS [  1.872 s]
[INFO] Hive Service RPC ................................... SUCCESS [  0.864 s]
[INFO] Hive Serde ......................................... SUCCESS [  1.393 s]
[INFO] Hive Metastore ..................................... SUCCESS [  6.799 s]
[INFO] Hive Vector-Code-Gen Utilities ..................... SUCCESS [  0.113 s]
[INFO] Hive Llap Common ................................... SUCCESS [  1.013 s]
[INFO] Hive Llap Client ................................... SUCCESS [  0.531 s]
[INFO] Hive Llap Tez ...................................... SUCCESS [  0.654 s]
[INFO] Spark Remote Client ................................ SUCCESS [  1.434 s]
[INFO] Hive Query Language ................................ SUCCESS [ 20.672 s]
[INFO] Hive Llap Server ................................... SUCCESS [  2.136 s]
[INFO] Hive Service ....................................... FAILURE [ 45.523 s]
[INFO] Hive Accumulo Handler .............................. SKIPPED
[INFO] Hive JDBC .......................................... SKIPPED
[INFO] Hive Beeline ....................................... SKIPPED
[INFO] Hive CLI ........................................... SKIPPED
[INFO] Hive Contrib ....................................... SKIPPED
[INFO] Hive Druid Handler ................................. SKIPPED
[INFO] Hive HBase Handler ................................. SKIPPED
[INFO] Hive JDBC Handler .................................. SKIPPED
[INFO] Hive HCatalog ...................................... SKIPPED
[INFO] Hive HCatalog Core ................................. SKIPPED
[INFO] Hive HCatalog Pig Adapter .......................... SKIPPED
[INFO] Hive HCatalog Server Extensions .................... SKIPPED
[INFO] Hive HCatalog Webhcat Java Client .................. SKIPPED
[INFO] Hive HCatalog Webhcat .............................. SKIPPED
[INFO] Hive HCatalog Streaming ............................ SKIPPED
[INFO] Hive HPL/SQL ....................................... SKIPPED
[INFO] Hive Llap External Client .......................... SKIPPED
[INFO] Hive Shims Aggregator .............................. SKIPPED
[INFO] Hive TestUtils ..................................... SKIPPED
[INFO] Hive Packaging ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:27 min
[INFO] Finished at: 2023-05-26T17:25:07Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hive-service: Could not resolve dependencies for project org.apache.hive:hive-service:jar:2.3.9-1.0: Failed to collect dependencies at org.apache.directory.server:apacheds-server-integ:jar:1.5.6 -> org.apache.directory.client.ldap:ldap-client-api:jar:0.1-SNAPSHOT: Failed to read artifact descriptor for org.apache.directory.client.ldap:ldap-client-api:jar:0.1-SNAPSHOT: Could not transfer artifact org.apache.directory.client.ldap:ldap-client-api:pom:0.1-SNAPSHOT from/to conjars (http://conjars.org/repo): Access denied to: http://conjars.org/repo/org/apache/directory/client/ldap/ldap-client-api/0.1-SNAPSHOT/ldap-client-api-0.1-SNAPSHOT.pom , ReasonPhrase:Forbidden. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hive-service
```

But this issue is solved if I run the build with this PR so this PR is useful.

**Review by rpignolet — APPROVED** [review]

**Pull request merged**
